### ISSUE TITLE
Commit 54c625c introduced regression

### ISSUE THREAD

**Issue by alemonmk** [kkapsner/CanvasBlocker#715]
## Description
[Reflect.setPrototypeOf](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/setPrototypeOf) takes `null` for argument `prototype`. However, the altered `setPrototypeOf()` called `getPrototypeOf()` which throws on `null` without a null check. Which caused an Uncaught TypeError in `near-membrane-shared` and could be stopping Grafana's (affected my 11.0, wikipedia's 9.5 is fine) web UI from loading. Disabling the plugin will let Grafana load properly.

## Expected Behaviour
Grafana UI should load properly.

## Current Behaviour
Grafana stopped loading and showing error message: "Grafana has failed to load its application files"

## Steps to Reproduce (for bugs)
1. Install CanvasBlocker
2. Visit a Grafana v11 installation

## Your Environment

* CanvasBlocker Version used: 1.10.1
* Firefox version incl. 32- or 64-bit: 64-bit
* Operating System and version (desktop or mobile): Windows 10 21H2
* Installed addons: CanvasBlocker, uBlock Origin, Referer Modifier, LocalCDN, Cookie Quick Manager, DownThemAll!, Duplicate Tabs Closer, Firefox Multi-Account Containers, HyperChat and PocketTube

## Your Settings
~~~ json
{
	"logLevel": 1,
	"urlSettings": [
		{
			"url": "challenges.cloudflare.com",
			"protectedCanvasPart": "nothing"
		}
	],
	"hiddenSettings": {
		"enableStackList": false,
		"protectedCanvasPart": false,
		"protectedAPIFeatures": false
	},
	"expandStatus": {
		"section_lists": true,
		"protectNavigator": true,
		"useAudioCache": false,
		"protectedCanvasPart": true,
		"protectAudio": false,
		"protectScreen": false
	},
	"displayHiddenSettings": true,
	"whiteList": "\n",
	"sessionWhiteList": "",
	"blackList": "",
	"blockMode": "fake",
	"protectedCanvasPart": "readout",
	"minFakeSize": 1,
	"maxFakeSize": 0,
	"rng": "nonPersistent",
	"protectedAPIFeatures": {},
	"useCanvasCache": true,
	"ignoreFrequentColors": 0,
	"minColors": 0,
	"fakeAlphaChannel": true,
	"webGLVendor": "",
	"webGLRenderer": "",
	"webGLUnmaskedVendor": "",
	"webGLUnmaskedRenderer": "",
	"persistentRndStorage": "",
	"persistentIncognitoRndStorage": "",
	"storePersistentRnd": false,
	"persistentRndClearIntervalValue": 0,
	"persistentRndClearIntervalUnit": "days",
	"lastPersistentRndClearing": 1719591123928,
	"sharePersistentRndBetweenDomains": false,
	"askOnlyOnce": "individual",
	"askDenyMode": "block",
	"showCanvasWhileAsking": true,
	"showNotifications": true,
	"highlightPageAction": "none",
	"highlightBrowserAction": "color",
	"displayBadge": false,
	"storeNotificationData": false,
	"storeImageForInspection": false,
	"ignoreList": "",
	"ignoredAPIs": {},
	"showCallingFile": false,
	"showCompleteCallingStack": false,
	"enableStackList": false,
	"stackList": "",
	"protectAudio": true,
	"audioFakeRate": "100",
	"audioNoiseLevel": "low",
	"useAudioCache": true,
	"audioUseFixedIndices": true,
	"audioFixedIndices": "6",
	"historyLengthThreshold": 2,
	"protectWindow": false,
	"allowWindowNameInFrames": false,
	"protectDOMRect": true,
	"domRectIntegerFactor": 4,
	"protectSVG": true,
	"protectTextMetrics": true,
	"blockDataURLs": true,
	"protectNavigator": false,
	"navigatorDetails": {},
	"protectScreen": true,
	"screenSize": "",
	"fakeMinimalScreenSize": true,
	"displayAdvancedSettings": true,
	"displayDescriptions": false,
	"theme": "auto",
	"showPresetsOnInstallation": true,
	"dontShowOptionsOnUpdate": false,
	"disruptSessionOnUpdate": false,
	"updatePending": false,
	"isStillDefault": false,
	"storageVersion": 1
}
~~~

**Comment by kkapsner** [comment]
3eedc7b7dc99f23c0db525b069a5cd5faaf5a75b should solve this problem. Please check with the latest alpha: https://canvasblocker.kkapsner.de/versions/?C=M;O=D

**Comment by alemonmk** [comment]
Hi @kkapsner, the fix is working, thank you for the prompt response.

**Comment by KiARC** [comment]
Any timeframe of when this will make it to stable? Whitelisting the site in question (also a Grafana instance for me) doesn't fix it, so I'd love to know when this will be released.

**Comment by kkapsner** [comment]
I hope the next two week allow me to submit the next version.
